# Generated by Django 4.0.4 on 2022-05-07 00:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('brief_description', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('technologies', models.CharField(max_length=100)),
                ('link', models.CharField(default='github.com/hwdecker', max_length=128)),
                ('image', models.ImageField(upload_to='project_pics')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
